name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  test:
    strategy:
      matrix:
        python: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]
    runs-on: 'ubuntu-latest'
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Reinstall Pip
      run: pip install --upgrade --force-reinstall pip
    - name: Install Test Deps
      run: pip install ".[test]"
    - name: Run tests
      run: |
        TOXENV="py$(echo '${{ matrix.python }}' | tr -d '.')"
        python -m tox -e $TOXENV
