name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-20.04' ]
        python: [ '3.11', '3.10', '3.9', '3.8', '3.7', '3.6' ]
        exclude:
          - os: 'ubuntu-latest'
            python: '3.6'
          - os: 'ubuntu-20.04'
            python: '3.11'
          - os: 'ubuntu-20.04'
            python: '3.10'
          - os: 'ubuntu-20.04'
            python: '3.9'
          - os: 'ubuntu-20.04'
            python: '3.8'
          - os: 'ubuntu-20.04'
            python: '3.7'
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install deps
      run: pip install --upgrade --force-reinstall pip
    - name: Run tests
      run: python setup.py test
